[package]
name = "pi-home-router"
version = "0.1.0"
authors = ["Collin Valley <collin.valley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
