language: rust
rust:
  - stable
cache: cargo
branches:
  only:
    - master
jobs:
  include:
    - stage: lint
      install: rustup component add rustfmt
      script: cargo fmt -- --check
    - stage: lint
      install: rustup component add clippy
      script: cargo clippy --all-targets -- -D warnings
    - stage: lint
      install: cargo install -f cargo-deny
      script: cargo deny check
    - stage: build
      script: cargo build --verbose
    - stage: test
      script: cargo test --verbose