language: rust
rust:
  - stable
cache: cargo
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      install: rustup component add rustfmt &&
                rustup component add clippy &&
                cargo install -f cargo-deny
      script: cargo fmt -- --check &&
                cargo clippy --all-targets -- -D warnings &&
                cargo deny check &&
                cargo build --verbose &&
                cargo test --verbose