language: rust
rust:
  - stable
cache: cargo
branches:
  only:
    - master
    - /^dev\//
jobs:
  include:
    - stage: test
      before_install: sudo apt-get update && sudo apt-get install -y libpcap-dev
      install: rustup component add rustfmt &&
                rustup component add clippy &&
                cargo install -f --version 0.6.6 cargo-deny
      script: cargo fmt -- --check &&
                cargo clippy --all-targets -- -D warnings &&
                cargo deny check &&
                cargo build --verbose &&
                cargo test --verbose
