[package]
name = "route-rs-runtime"
version = "0.1.0"
authors = ["Collin Valley <collin.valley@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
tokio = "*"
futures = "*"
crossbeam = "*"
smoltcp = "0.5.0"